Repository oakleywindiate/whats-cookin, pull requests merged in 2022-04, with the labels that each got.

#31 Features/user favorite recipes/nb
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/classes/UserRepository.js
  test/RecipeRepository-test.js
  test/User-test.js
  test/UserRepository-test.js
Labels: MVP, set-up

#32 Create test and method for filtering name and tags
  src/classes/User.js
  test/User-test.js
Labels: MVP, set-up

#35 Feature/add recipes to cook/rh
  dist/index.html
  src/classes/User.js
  src/scripts.js
  src/styles.css
  test/User-test.js
  test/UserRepository-test.js
Labels: MVP, set-up

#39 Feature/favorite recipes/rh
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: MVP, set-up

#45 Feature/recipes to cook/ow
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: MVP, set-up, Dashboard

#47 Feature/fetch data/nb
  dist/index.html
  src/apiCalls.js
  src/scripts.js
Labels: MVP, set-up

#48 Feature/css styling
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement, MVP, set-up

#49 Add CSS styling
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#50 Bug/favoriting issues
  dist/index.html
  src/classes/User.js
  src/scripts.js
  src/styles.css
Labels: bug

#51 Refactor/clean cde/nb
  dist/index.html
  src/apiCalls.js
  src/classes/Ingredient.js
  src/classes/Recipe.js
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/classes/UserRepository.js
  src/data/ingredients.js
  src/data/recipes.js
  src/data/users.js
  src/scripts.js
  test/Ingredient-test.js
  test/Recipe-test.js
  test/RecipeRepository-test.js
  test/User-test.js
  test/UserRepository-test.js
Labels: bug

#52 Complete CSS styling
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#53 Write README
  README.md
Labels: MVP, set-up

#62 Feature/feedback/rh
  dist/index.html
  src/classes/Recipe.js
  src/classes/RecipeRepository.js
  src/scripts.js
  src/styles.css
  test/User-test.js
Labels: enhancement, high priority

#64 Feature/pantry page/ow
  dist/index.html
  src/classes/User.js
  src/scripts.js
  src/styles.css
  test/User-test.js
Labels: enhancement, MVP

#67 Feature/user pantry issue/ow
  src/apiCalls.js
  src/classes/User.js
  test/User-test.js
Labels: MVP

#68 Feature/pantry user story/rh
  dist/index.html
  src/apiCalls.js
  src/classes/User.js
  src/scripts.js
  src/styles.css
  test/User-test.js
Labels: MVP, set-up, DOM

#73 Feature/api post issue/nb
  src/apiCalls.js
  src/scripts.js
Labels: MVP

#79 Feature/error handling/nb
  dist/index.html
  src/apiCalls.js
  src/classes/User.js
  src/scripts.js
  src/styles.css
Labels: bug, MVP

#80 Refactor/dom updates/ow
  src/apiCalls.js
  src/domUpdates.js
  src/scripts.js
Labels: enhancement, MVP, DOM

#82 Refactor/clean tests/nb
  dist/index.html
  src/apiCalls.js
  src/classes/User.js
  src/domUpdates.js
  src/scripts.js
  src/styles.css
  test/Ingredient-test.js
  test/Recipe-test.js
  test/RecipeRepository-test.js
  test/User-test.js
  test/UserRepository-test.js
  test/test-data.js
Labels: bug
